### ISSUE TITLE
Jenkins maintenance

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-core#1224]
**Jenkins maintenance**

- [ ] Update plugins - https://github.com/opendevstack/ods-core/pull/1235
- [ ] Update Jenkins version and aling with base agent - https://github.com/opendevstack/ods-core/pull/1235
- [ ] Align Aquacli version #1219 
- [ ]  Update Git LFS #1206 
- [x]  Remove legacy configuration and plugins - #1225
- [x] Configure durability for max performance - https://github.com/opendevstack/ods-core/pull/1225
- [x] Update resources for deployment (~~Currently testing to ensure estability~~) - https://github.com/opendevstack/ods-core/pull/1234
